import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { registerFonts } from './fonts';
import { pdfStyles } from './styles';
import { renderMarkdown } from './render-markdown';
import type { DoctorReport, CulturalFlag } from '@/lib/types';

registerFonts();

interface DoctorReportPdfProps {
  report: DoctorReport;
  patientName?: string | null;
  culturalFlags?: CulturalFlag[];
}

export function DoctorReportPdf({ report, patientName, culturalFlags }: DoctorReportPdfProps) {
  const visitDate = new Date(report.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const langLabel = `${report.languagePair.provider} / ${report.languagePair.patient}`;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>Entune — SOAP Note</Text>
          <Text style={pdfStyles.subtitle}>
            {visitDate}
            {patientName ? `  |  Patient: ${patientName}` : ''}
            {`  |  Languages: ${langLabel}`}
          </Text>
        </View>

        {/* Subjective */}
        <Text style={pdfStyles.sectionTitle}>Subjective</Text>
        <View>{renderMarkdown(report.subjective)}</View>

        <View style={pdfStyles.divider} />

        {/* Objective */}
        <Text style={pdfStyles.sectionTitle}>Objective</Text>
        <View>{renderMarkdown(report.objective)}</View>

        <View style={pdfStyles.divider} />

        {/* Assessment */}
        <Text style={pdfStyles.sectionTitle}>Assessment</Text>
        <View>{renderMarkdown(report.assessment)}</View>

        <View style={pdfStyles.divider} />

        {/* Plan */}
        <Text style={pdfStyles.sectionTitle}>Plan</Text>
        <View>{renderMarkdown(report.plan)}</View>

        {/* Cultural Considerations */}
        {report.culturalConsiderations && (
          <>
            <View style={pdfStyles.divider} />
            <Text style={pdfStyles.sectionTitle}>Cultural Considerations</Text>
            <View>{renderMarkdown(report.culturalConsiderations)}</View>
          </>
        )}

        {/* Cultural Flags */}
        {culturalFlags && culturalFlags.length > 0 && (
          <>
            <View style={pdfStyles.divider} />
            <Text style={pdfStyles.sectionTitle}>Cultural Flags Detected</Text>
            {culturalFlags.map((flag, i) => (
              <View key={i} style={pdfStyles.flagBox}>
                <Text style={pdfStyles.flagTerm}>
                  {flag.term} — {flag.literal}
                </Text>
                <Text style={pdfStyles.flagDetail}>{flag.clinicalContext}</Text>
                {flag.screenFor.length > 0 && (
                  <Text style={pdfStyles.flagDetail}>
                    Screen for: {flag.screenFor.join(', ')}
                  </Text>
                )}
                {flag.safetyNote && (
                  <Text style={pdfStyles.flagDetail}>Safety: {flag.safetyNote}</Text>
                )}
              </View>
            ))}
          </>
        )}

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text style={pdfStyles.footerText}>
            Generated by Entune on {visitDate}. This document is for provider reference only.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
