import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { registerFonts } from './fonts';
import { pdfStyles } from './styles';
import type { PatientReport } from '@/lib/types';

registerFonts();

const sectionTitles: Record<string, Record<string, string>> = {
  summary: { 'en-US': 'Visit Summary', 'ko-KR': '진료 요약', 'es-ES': 'Resumen de la Visita' },
  medications: { 'en-US': 'Medications', 'ko-KR': '처방약', 'es-ES': 'Medicamentos' },
  followUps: { 'en-US': 'Follow-Ups', 'ko-KR': '후속 조치', 'es-ES': 'Seguimientos' },
  warnings: { 'en-US': 'Warning Signs', 'ko-KR': '주의 증상', 'es-ES': 'Señales de Advertencia' },
};

function t(section: string, lang: string): string {
  return sectionTitles[section]?.[lang] || sectionTitles[section]?.['en-US'] || section;
}

interface PatientReportPdfProps {
  report: PatientReport;
}

export function PatientReportPdf({ report }: PatientReportPdfProps) {
  const lang = report.language || 'en-US';
  const isKorean = lang === 'ko-KR';
  const pageStyle = isKorean ? pdfStyles.pageKorean : pdfStyles.page;

  const visitDate = new Date(report.generatedAt).toLocaleDateString(
    lang === 'ko-KR' ? 'ko-KR' : lang === 'es-ES' ? 'es-ES' : 'en-US',
    { year: 'numeric', month: 'long', day: 'numeric' },
  );

  return (
    <Document>
      <Page size="A4" style={pageStyle}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>Entune</Text>
          <Text style={pdfStyles.subtitle}>{visitDate}</Text>
        </View>

        {/* Summary */}
        <Text style={pdfStyles.sectionTitle}>{t('summary', lang)}</Text>
        <Text style={pdfStyles.body}>{report.summary}</Text>

        {/* Medications */}
        {report.medications.length > 0 && (
          <>
            <View style={pdfStyles.divider} />
            <Text style={pdfStyles.sectionTitle}>{t('medications', lang)}</Text>
            {report.medications.map((med, i) => (
              <View key={i} style={pdfStyles.medItem}>
                <Text style={pdfStyles.medName}>{med.name}</Text>
                <Text style={pdfStyles.medInstructions}>{med.instructions}</Text>
              </View>
            ))}
          </>
        )}

        {/* Follow-Ups */}
        {report.followUps.length > 0 && (
          <>
            <View style={pdfStyles.divider} />
            <Text style={pdfStyles.sectionTitle}>{t('followUps', lang)}</Text>
            {report.followUps.map((fu, i) => (
              <View key={i} style={pdfStyles.followUpRow}>
                <Text style={pdfStyles.body}>{fu.item}</Text>
                {fu.date && <Text style={pdfStyles.followUpDate}>{fu.date}</Text>}
              </View>
            ))}
          </>
        )}

        {/* Warning Signs */}
        {report.warningSignsToWatchFor.length > 0 && (
          <View style={pdfStyles.warningBox}>
            <Text style={pdfStyles.warningTitle}>{t('warnings', lang)}</Text>
            {report.warningSignsToWatchFor.map((sign, i) => (
              <Text key={i} style={pdfStyles.warningItem}>
                {'\u2022 '}{sign}
              </Text>
            ))}
          </View>
        )}

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text style={pdfStyles.footerText}>
            Generated by Entune on {visitDate}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
