import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { registerFonts } from './fonts';
import { pdfStyles } from './styles';

registerFonts();

interface TranscriptEntry {
  speaker: 'patient' | 'provider';
  original_text: string;
  translated_text: string;
  timestamp: string;
}

interface TranscriptPdfProps {
  transcript: TranscriptEntry[];
  patientName?: string | null;
  visitDate: string;
  patientLanguage: string;
  providerLanguage: string;
}

const LANGUAGE_LABELS: Record<string, string> = {
  'en-US': 'English',
  'ko-KR': 'Korean',
  'es-ES': 'Spanish',
};

export function TranscriptPdf({
  transcript,
  patientName,
  visitDate,
  patientLanguage,
  providerLanguage,
}: TranscriptPdfProps) {
  const dateLabel = new Date(visitDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const timeLabel = new Date(visitDate).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
  });

  const langLabel = `${LANGUAGE_LABELS[patientLanguage] || patientLanguage} / ${LANGUAGE_LABELS[providerLanguage] || providerLanguage}`;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page} wrap>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.title}>Entune — Transcript</Text>
          <Text style={pdfStyles.subtitle}>
            {dateLabel} at {timeLabel}
            {patientName ? `  |  Patient: ${patientName}` : ''}
            {`  |  Languages: ${langLabel}`}
          </Text>
        </View>

        {/* Entries */}
        {transcript.map((entry, i) => {
          const time = new Date(entry.timestamp).toLocaleTimeString('en-US', {
            hour: 'numeric',
            minute: '2-digit',
            second: '2-digit',
          });
          const speakerLabel = entry.speaker === 'provider' ? 'Provider' : 'Patient';
          const showTranslation = entry.original_text !== entry.translated_text;

          return (
            <View
              key={i}
              style={{
                marginBottom: 8,
                paddingBottom: 8,
                borderBottomWidth: i < transcript.length - 1 ? 1 : 0,
                borderBottomColor: '#e2e8f0',
              }}
              wrap={false}
            >
              <View style={{ flexDirection: 'row', marginBottom: 2 }}>
                <Text style={{ fontSize: 9, color: '#64748b' }}>{time}</Text>
                <Text style={{ fontSize: 9, fontWeight: 700, marginLeft: 8 }}>
                  {speakerLabel}
                </Text>
              </View>
              <Text style={pdfStyles.body}>{entry.original_text}</Text>
              {showTranslation && (
                <Text style={{ fontSize: 9, color: '#64748b', marginTop: 2, fontStyle: 'italic' }}>
                  {entry.translated_text}
                </Text>
              )}
            </View>
          );
        })}

        {/* Footer */}
        <View style={pdfStyles.footer} fixed>
          <Text style={pdfStyles.footerText}>
            Generated by Entune on {dateLabel}. {transcript.length} entries.
          </Text>
        </View>
      </Page>
    </Document>
  );
}
