#!/bin/bash
# Auto-generated by n2o init — sources project config for use in skills/scripts.
# Usage: source scripts/n2o-config.sh

_N2O_CONFIG=".pm/config.json"

if [[ ! -f "$_N2O_CONFIG" ]]; then
  echo "Error: $_N2O_CONFIG not found. Are you in the project root?" >&2
  return 1 2>/dev/null || exit 1
fi

export N2O_VERSION=$(jq -r '.n2o_version' "$_N2O_CONFIG")
export N2O_PROJECT=$(jq -r '.project_name' "$_N2O_CONFIG")
export N2O_TEST_CMD=$(jq -r '.commands.test // ""' "$_N2O_CONFIG")
export N2O_TYPECHECK_CMD=$(jq -r '.commands.typecheck // ""' "$_N2O_CONFIG")
export N2O_LINT_CMD=$(jq -r '.commands.lint // ""' "$_N2O_CONFIG")
export N2O_BUILD_CMD=$(jq -r '.commands.build // ""' "$_N2O_CONFIG")
